# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/song/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.5153.40/CLion.app/Contents/bin/cmake/mac/bin/cmake"

# The command to remove a file.
RM = "/Users/song/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.5153.40/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/song/Dropbox/gean

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/song/Dropbox/gean

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/song/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.5153.40/CLion.app/Contents/bin/cmake/mac/bin/cmake" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/song/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/183.5153.40/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/song/Dropbox/gean/CMakeFiles /Users/song/Dropbox/gean/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/song/Dropbox/gean/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gean

# Build rule for target.
gean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gean
.PHONY : gean

# fast build rule for target.
gean/fast:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/build
.PHONY : gean/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

song.o: song.cpp.o

.PHONY : song.o

# target to build an object file
song.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/song.cpp.o
.PHONY : song.cpp.o

song.i: song.cpp.i

.PHONY : song.i

# target to preprocess a source file
song.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/song.cpp.i
.PHONY : song.cpp.i

song.s: song.cpp.s

.PHONY : song.s

# target to generate assembly for a file
song.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/song.cpp.s
.PHONY : song.cpp.s

src/InputParser.o: src/InputParser.cpp.o

.PHONY : src/InputParser.o

# target to build an object file
src/InputParser.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/InputParser.cpp.o
.PHONY : src/InputParser.cpp.o

src/InputParser.i: src/InputParser.cpp.i

.PHONY : src/InputParser.i

# target to preprocess a source file
src/InputParser.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/InputParser.cpp.i
.PHONY : src/InputParser.cpp.i

src/InputParser.s: src/InputParser.cpp.s

.PHONY : src/InputParser.s

# target to generate assembly for a file
src/InputParser.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/InputParser.cpp.s
.PHONY : src/InputParser.cpp.s

src/cns.o: src/cns.cpp.o

.PHONY : src/cns.o

# target to build an object file
src/cns.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/cns.cpp.o
.PHONY : src/cns.cpp.o

src/cns.i: src/cns.cpp.i

.PHONY : src/cns.i

# target to preprocess a source file
src/cns.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/cns.cpp.i
.PHONY : src/cns.cpp.i

src/cns.s: src/cns.cpp.s

.PHONY : src/cns.s

# target to generate assembly for a file
src/cns.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/cns.cpp.s
.PHONY : src/cns.cpp.s

src/control/VariantsCountAsPhenotypeForAssociation.o: src/control/VariantsCountAsPhenotypeForAssociation.cpp.o

.PHONY : src/control/VariantsCountAsPhenotypeForAssociation.o

# target to build an object file
src/control/VariantsCountAsPhenotypeForAssociation.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/control/VariantsCountAsPhenotypeForAssociation.cpp.o
.PHONY : src/control/VariantsCountAsPhenotypeForAssociation.cpp.o

src/control/VariantsCountAsPhenotypeForAssociation.i: src/control/VariantsCountAsPhenotypeForAssociation.cpp.i

.PHONY : src/control/VariantsCountAsPhenotypeForAssociation.i

# target to preprocess a source file
src/control/VariantsCountAsPhenotypeForAssociation.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/control/VariantsCountAsPhenotypeForAssociation.cpp.i
.PHONY : src/control/VariantsCountAsPhenotypeForAssociation.cpp.i

src/control/VariantsCountAsPhenotypeForAssociation.s: src/control/VariantsCountAsPhenotypeForAssociation.cpp.s

.PHONY : src/control/VariantsCountAsPhenotypeForAssociation.s

# target to generate assembly for a file
src/control/VariantsCountAsPhenotypeForAssociation.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/control/VariantsCountAsPhenotypeForAssociation.cpp.s
.PHONY : src/control/VariantsCountAsPhenotypeForAssociation.cpp.s

src/control/myCoordinateLiftOver.o: src/control/myCoordinateLiftOver.cpp.o

.PHONY : src/control/myCoordinateLiftOver.o

# target to build an object file
src/control/myCoordinateLiftOver.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/control/myCoordinateLiftOver.cpp.o
.PHONY : src/control/myCoordinateLiftOver.cpp.o

src/control/myCoordinateLiftOver.i: src/control/myCoordinateLiftOver.cpp.i

.PHONY : src/control/myCoordinateLiftOver.i

# target to preprocess a source file
src/control/myCoordinateLiftOver.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/control/myCoordinateLiftOver.cpp.i
.PHONY : src/control/myCoordinateLiftOver.cpp.i

src/control/myCoordinateLiftOver.s: src/control/myCoordinateLiftOver.cpp.s

.PHONY : src/control/myCoordinateLiftOver.s

# target to generate assembly for a file
src/control/myCoordinateLiftOver.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/control/myCoordinateLiftOver.cpp.s
.PHONY : src/control/myCoordinateLiftOver.cpp.s

src/control/myReAnnotationAndExonerateAndNovo.o: src/control/myReAnnotationAndExonerateAndNovo.cpp.o

.PHONY : src/control/myReAnnotationAndExonerateAndNovo.o

# target to build an object file
src/control/myReAnnotationAndExonerateAndNovo.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/control/myReAnnotationAndExonerateAndNovo.cpp.o
.PHONY : src/control/myReAnnotationAndExonerateAndNovo.cpp.o

src/control/myReAnnotationAndExonerateAndNovo.i: src/control/myReAnnotationAndExonerateAndNovo.cpp.i

.PHONY : src/control/myReAnnotationAndExonerateAndNovo.i

# target to preprocess a source file
src/control/myReAnnotationAndExonerateAndNovo.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/control/myReAnnotationAndExonerateAndNovo.cpp.i
.PHONY : src/control/myReAnnotationAndExonerateAndNovo.cpp.i

src/control/myReAnnotationAndExonerateAndNovo.s: src/control/myReAnnotationAndExonerateAndNovo.cpp.s

.PHONY : src/control/myReAnnotationAndExonerateAndNovo.s

# target to generate assembly for a file
src/control/myReAnnotationAndExonerateAndNovo.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/control/myReAnnotationAndExonerateAndNovo.cpp.s
.PHONY : src/control/myReAnnotationAndExonerateAndNovo.cpp.s

src/controlLayer.o: src/controlLayer.cpp.o

.PHONY : src/controlLayer.o

# target to build an object file
src/controlLayer.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/controlLayer.cpp.o
.PHONY : src/controlLayer.cpp.o

src/controlLayer.i: src/controlLayer.cpp.i

.PHONY : src/controlLayer.i

# target to preprocess a source file
src/controlLayer.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/controlLayer.cpp.i
.PHONY : src/controlLayer.cpp.i

src/controlLayer.s: src/controlLayer.cpp.s

.PHONY : src/controlLayer.s

# target to generate assembly for a file
src/controlLayer.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/controlLayer.cpp.s
.PHONY : src/controlLayer.cpp.s

src/impl/CheckAndUpdateTranscriptsEnds.o: src/impl/CheckAndUpdateTranscriptsEnds.cpp.o

.PHONY : src/impl/CheckAndUpdateTranscriptsEnds.o

# target to build an object file
src/impl/CheckAndUpdateTranscriptsEnds.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/CheckAndUpdateTranscriptsEnds.cpp.o
.PHONY : src/impl/CheckAndUpdateTranscriptsEnds.cpp.o

src/impl/CheckAndUpdateTranscriptsEnds.i: src/impl/CheckAndUpdateTranscriptsEnds.cpp.i

.PHONY : src/impl/CheckAndUpdateTranscriptsEnds.i

# target to preprocess a source file
src/impl/CheckAndUpdateTranscriptsEnds.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/CheckAndUpdateTranscriptsEnds.cpp.i
.PHONY : src/impl/CheckAndUpdateTranscriptsEnds.cpp.i

src/impl/CheckAndUpdateTranscriptsEnds.s: src/impl/CheckAndUpdateTranscriptsEnds.cpp.s

.PHONY : src/impl/CheckAndUpdateTranscriptsEnds.s

# target to generate assembly for a file
src/impl/CheckAndUpdateTranscriptsEnds.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/CheckAndUpdateTranscriptsEnds.cpp.s
.PHONY : src/impl/CheckAndUpdateTranscriptsEnds.cpp.s

src/impl/FileWriteCatch.o: src/impl/FileWriteCatch.cpp.o

.PHONY : src/impl/FileWriteCatch.o

# target to build an object file
src/impl/FileWriteCatch.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/FileWriteCatch.cpp.o
.PHONY : src/impl/FileWriteCatch.cpp.o

src/impl/FileWriteCatch.i: src/impl/FileWriteCatch.cpp.i

.PHONY : src/impl/FileWriteCatch.i

# target to preprocess a source file
src/impl/FileWriteCatch.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/FileWriteCatch.cpp.i
.PHONY : src/impl/FileWriteCatch.cpp.i

src/impl/FileWriteCatch.s: src/impl/FileWriteCatch.cpp.s

.PHONY : src/impl/FileWriteCatch.s

# target to generate assembly for a file
src/impl/FileWriteCatch.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/FileWriteCatch.cpp.s
.PHONY : src/impl/FileWriteCatch.cpp.s

src/impl/GetPseudoGenomeSequence.o: src/impl/GetPseudoGenomeSequence.cpp.o

.PHONY : src/impl/GetPseudoGenomeSequence.o

# target to build an object file
src/impl/GetPseudoGenomeSequence.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/GetPseudoGenomeSequence.cpp.o
.PHONY : src/impl/GetPseudoGenomeSequence.cpp.o

src/impl/GetPseudoGenomeSequence.i: src/impl/GetPseudoGenomeSequence.cpp.i

.PHONY : src/impl/GetPseudoGenomeSequence.i

# target to preprocess a source file
src/impl/GetPseudoGenomeSequence.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/GetPseudoGenomeSequence.cpp.i
.PHONY : src/impl/GetPseudoGenomeSequence.cpp.i

src/impl/GetPseudoGenomeSequence.s: src/impl/GetPseudoGenomeSequence.cpp.s

.PHONY : src/impl/GetPseudoGenomeSequence.s

# target to generate assembly for a file
src/impl/GetPseudoGenomeSequence.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/GetPseudoGenomeSequence.cpp.s
.PHONY : src/impl/GetPseudoGenomeSequence.cpp.s

src/impl/GetReverseComplementary.o: src/impl/GetReverseComplementary.cpp.o

.PHONY : src/impl/GetReverseComplementary.o

# target to build an object file
src/impl/GetReverseComplementary.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/GetReverseComplementary.cpp.o
.PHONY : src/impl/GetReverseComplementary.cpp.o

src/impl/GetReverseComplementary.i: src/impl/GetReverseComplementary.cpp.i

.PHONY : src/impl/GetReverseComplementary.i

# target to preprocess a source file
src/impl/GetReverseComplementary.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/GetReverseComplementary.cpp.i
.PHONY : src/impl/GetReverseComplementary.cpp.i

src/impl/GetReverseComplementary.s: src/impl/GetReverseComplementary.cpp.s

.PHONY : src/impl/GetReverseComplementary.s

# target to generate assembly for a file
src/impl/GetReverseComplementary.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/GetReverseComplementary.cpp.s
.PHONY : src/impl/GetReverseComplementary.cpp.s

src/impl/NucmerRead.o: src/impl/NucmerRead.cpp.o

.PHONY : src/impl/NucmerRead.o

# target to build an object file
src/impl/NucmerRead.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/NucmerRead.cpp.o
.PHONY : src/impl/NucmerRead.cpp.o

src/impl/NucmerRead.i: src/impl/NucmerRead.cpp.i

.PHONY : src/impl/NucmerRead.i

# target to preprocess a source file
src/impl/NucmerRead.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/NucmerRead.cpp.i
.PHONY : src/impl/NucmerRead.cpp.i

src/impl/NucmerRead.s: src/impl/NucmerRead.cpp.s

.PHONY : src/impl/NucmerRead.s

# target to generate assembly for a file
src/impl/NucmerRead.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/NucmerRead.cpp.s
.PHONY : src/impl/NucmerRead.cpp.s

src/impl/TranscriptUpdateInformation.o: src/impl/TranscriptUpdateInformation.cpp.o

.PHONY : src/impl/TranscriptUpdateInformation.o

# target to build an object file
src/impl/TranscriptUpdateInformation.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/TranscriptUpdateInformation.cpp.o
.PHONY : src/impl/TranscriptUpdateInformation.cpp.o

src/impl/TranscriptUpdateInformation.i: src/impl/TranscriptUpdateInformation.cpp.i

.PHONY : src/impl/TranscriptUpdateInformation.i

# target to preprocess a source file
src/impl/TranscriptUpdateInformation.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/TranscriptUpdateInformation.cpp.i
.PHONY : src/impl/TranscriptUpdateInformation.cpp.i

src/impl/TranscriptUpdateInformation.s: src/impl/TranscriptUpdateInformation.cpp.s

.PHONY : src/impl/TranscriptUpdateInformation.s

# target to generate assembly for a file
src/impl/TranscriptUpdateInformation.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/TranscriptUpdateInformation.cpp.s
.PHONY : src/impl/TranscriptUpdateInformation.cpp.s

src/impl/WriteFasta.o: src/impl/WriteFasta.cpp.o

.PHONY : src/impl/WriteFasta.o

# target to build an object file
src/impl/WriteFasta.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/WriteFasta.cpp.o
.PHONY : src/impl/WriteFasta.cpp.o

src/impl/WriteFasta.i: src/impl/WriteFasta.cpp.i

.PHONY : src/impl/WriteFasta.i

# target to preprocess a source file
src/impl/WriteFasta.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/WriteFasta.cpp.i
.PHONY : src/impl/WriteFasta.cpp.i

src/impl/WriteFasta.s: src/impl/WriteFasta.cpp.s

.PHONY : src/impl/WriteFasta.s

# target to generate assembly for a file
src/impl/WriteFasta.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/WriteFasta.cpp.s
.PHONY : src/impl/WriteFasta.cpp.s

src/impl/annotationLiftOver.o: src/impl/annotationLiftOver.cpp.o

.PHONY : src/impl/annotationLiftOver.o

# target to build an object file
src/impl/annotationLiftOver.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/annotationLiftOver.cpp.o
.PHONY : src/impl/annotationLiftOver.cpp.o

src/impl/annotationLiftOver.i: src/impl/annotationLiftOver.cpp.i

.PHONY : src/impl/annotationLiftOver.i

# target to preprocess a source file
src/impl/annotationLiftOver.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/annotationLiftOver.cpp.i
.PHONY : src/impl/annotationLiftOver.cpp.i

src/impl/annotationLiftOver.s: src/impl/annotationLiftOver.cpp.s

.PHONY : src/impl/annotationLiftOver.s

# target to generate assembly for a file
src/impl/annotationLiftOver.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/annotationLiftOver.cpp.s
.PHONY : src/impl/annotationLiftOver.cpp.s

src/impl/checkOrfState.o: src/impl/checkOrfState.cpp.o

.PHONY : src/impl/checkOrfState.o

# target to build an object file
src/impl/checkOrfState.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/checkOrfState.cpp.o
.PHONY : src/impl/checkOrfState.cpp.o

src/impl/checkOrfState.i: src/impl/checkOrfState.cpp.i

.PHONY : src/impl/checkOrfState.i

# target to preprocess a source file
src/impl/checkOrfState.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/checkOrfState.cpp.i
.PHONY : src/impl/checkOrfState.cpp.i

src/impl/checkOrfState.s: src/impl/checkOrfState.cpp.s

.PHONY : src/impl/checkOrfState.s

# target to generate assembly for a file
src/impl/checkOrfState.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/checkOrfState.cpp.s
.PHONY : src/impl/checkOrfState.cpp.s

src/impl/coordinateLiftOver.o: src/impl/coordinateLiftOver.cpp.o

.PHONY : src/impl/coordinateLiftOver.o

# target to build an object file
src/impl/coordinateLiftOver.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/coordinateLiftOver.cpp.o
.PHONY : src/impl/coordinateLiftOver.cpp.o

src/impl/coordinateLiftOver.i: src/impl/coordinateLiftOver.cpp.i

.PHONY : src/impl/coordinateLiftOver.i

# target to preprocess a source file
src/impl/coordinateLiftOver.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/coordinateLiftOver.cpp.i
.PHONY : src/impl/coordinateLiftOver.cpp.i

src/impl/coordinateLiftOver.s: src/impl/coordinateLiftOver.cpp.s

.PHONY : src/impl/coordinateLiftOver.s

# target to generate assembly for a file
src/impl/coordinateLiftOver.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/coordinateLiftOver.cpp.s
.PHONY : src/impl/coordinateLiftOver.cpp.s

src/impl/deNovoGenomeVariantCalling.o: src/impl/deNovoGenomeVariantCalling.cpp.o

.PHONY : src/impl/deNovoGenomeVariantCalling.o

# target to build an object file
src/impl/deNovoGenomeVariantCalling.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/deNovoGenomeVariantCalling.cpp.o
.PHONY : src/impl/deNovoGenomeVariantCalling.cpp.o

src/impl/deNovoGenomeVariantCalling.i: src/impl/deNovoGenomeVariantCalling.cpp.i

.PHONY : src/impl/deNovoGenomeVariantCalling.i

# target to preprocess a source file
src/impl/deNovoGenomeVariantCalling.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/deNovoGenomeVariantCalling.cpp.i
.PHONY : src/impl/deNovoGenomeVariantCalling.cpp.i

src/impl/deNovoGenomeVariantCalling.s: src/impl/deNovoGenomeVariantCalling.cpp.s

.PHONY : src/impl/deNovoGenomeVariantCalling.s

# target to generate assembly for a file
src/impl/deNovoGenomeVariantCalling.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/deNovoGenomeVariantCalling.cpp.s
.PHONY : src/impl/deNovoGenomeVariantCalling.cpp.s

src/impl/getSequencesFromGff.o: src/impl/getSequencesFromGff.cpp.o

.PHONY : src/impl/getSequencesFromGff.o

# target to build an object file
src/impl/getSequencesFromGff.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/getSequencesFromGff.cpp.o
.PHONY : src/impl/getSequencesFromGff.cpp.o

src/impl/getSequencesFromGff.i: src/impl/getSequencesFromGff.cpp.i

.PHONY : src/impl/getSequencesFromGff.i

# target to preprocess a source file
src/impl/getSequencesFromGff.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/getSequencesFromGff.cpp.i
.PHONY : src/impl/getSequencesFromGff.cpp.i

src/impl/getSequencesFromGff.s: src/impl/getSequencesFromGff.cpp.s

.PHONY : src/impl/getSequencesFromGff.s

# target to generate assembly for a file
src/impl/getSequencesFromGff.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/getSequencesFromGff.cpp.s
.PHONY : src/impl/getSequencesFromGff.cpp.s

src/impl/getSubsequence.o: src/impl/getSubsequence.cpp.o

.PHONY : src/impl/getSubsequence.o

# target to build an object file
src/impl/getSubsequence.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/getSubsequence.cpp.o
.PHONY : src/impl/getSubsequence.cpp.o

src/impl/getSubsequence.i: src/impl/getSubsequence.cpp.i

.PHONY : src/impl/getSubsequence.i

# target to preprocess a source file
src/impl/getSubsequence.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/getSubsequence.cpp.i
.PHONY : src/impl/getSubsequence.cpp.i

src/impl/getSubsequence.s: src/impl/getSubsequence.cpp.s

.PHONY : src/impl/getSubsequence.s

# target to generate assembly for a file
src/impl/getSubsequence.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/getSubsequence.cpp.s
.PHONY : src/impl/getSubsequence.cpp.s

src/impl/nA2AA.o: src/impl/nA2AA.cpp.o

.PHONY : src/impl/nA2AA.o

# target to build an object file
src/impl/nA2AA.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/nA2AA.cpp.o
.PHONY : src/impl/nA2AA.cpp.o

src/impl/nA2AA.i: src/impl/nA2AA.cpp.i

.PHONY : src/impl/nA2AA.i

# target to preprocess a source file
src/impl/nA2AA.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/nA2AA.cpp.i
.PHONY : src/impl/nA2AA.cpp.i

src/impl/nA2AA.s: src/impl/nA2AA.cpp.s

.PHONY : src/impl/nA2AA.s

# target to generate assembly for a file
src/impl/nA2AA.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/nA2AA.cpp.s
.PHONY : src/impl/nA2AA.cpp.s

src/impl/organizeGffRecords.o: src/impl/organizeGffRecords.cpp.o

.PHONY : src/impl/organizeGffRecords.o

# target to build an object file
src/impl/organizeGffRecords.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/organizeGffRecords.cpp.o
.PHONY : src/impl/organizeGffRecords.cpp.o

src/impl/organizeGffRecords.i: src/impl/organizeGffRecords.cpp.i

.PHONY : src/impl/organizeGffRecords.i

# target to preprocess a source file
src/impl/organizeGffRecords.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/organizeGffRecords.cpp.i
.PHONY : src/impl/organizeGffRecords.cpp.i

src/impl/organizeGffRecords.s: src/impl/organizeGffRecords.cpp.s

.PHONY : src/impl/organizeGffRecords.s

# target to generate assembly for a file
src/impl/organizeGffRecords.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/organizeGffRecords.cpp.s
.PHONY : src/impl/organizeGffRecords.cpp.s

src/impl/readFastaFile.o: src/impl/readFastaFile.cpp.o

.PHONY : src/impl/readFastaFile.o

# target to build an object file
src/impl/readFastaFile.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/readFastaFile.cpp.o
.PHONY : src/impl/readFastaFile.cpp.o

src/impl/readFastaFile.i: src/impl/readFastaFile.cpp.i

.PHONY : src/impl/readFastaFile.i

# target to preprocess a source file
src/impl/readFastaFile.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/readFastaFile.cpp.i
.PHONY : src/impl/readFastaFile.cpp.i

src/impl/readFastaFile.s: src/impl/readFastaFile.cpp.s

.PHONY : src/impl/readFastaFile.s

# target to generate assembly for a file
src/impl/readFastaFile.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/readFastaFile.cpp.s
.PHONY : src/impl/readFastaFile.cpp.s

src/impl/readGffFile.o: src/impl/readGffFile.cpp.o

.PHONY : src/impl/readGffFile.o

# target to build an object file
src/impl/readGffFile.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/readGffFile.cpp.o
.PHONY : src/impl/readGffFile.cpp.o

src/impl/readGffFile.i: src/impl/readGffFile.cpp.i

.PHONY : src/impl/readGffFile.i

# target to preprocess a source file
src/impl/readGffFile.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/readGffFile.cpp.i
.PHONY : src/impl/readGffFile.cpp.i

src/impl/readGffFile.s: src/impl/readGffFile.cpp.s

.PHONY : src/impl/readGffFile.s

# target to generate assembly for a file
src/impl/readGffFile.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/readGffFile.cpp.s
.PHONY : src/impl/readGffFile.cpp.s

src/impl/readGffFileWithEverything.o: src/impl/readGffFileWithEverything.cpp.o

.PHONY : src/impl/readGffFileWithEverything.o

# target to build an object file
src/impl/readGffFileWithEverything.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/readGffFileWithEverything.cpp.o
.PHONY : src/impl/readGffFileWithEverything.cpp.o

src/impl/readGffFileWithEverything.i: src/impl/readGffFileWithEverything.cpp.i

.PHONY : src/impl/readGffFileWithEverything.i

# target to preprocess a source file
src/impl/readGffFileWithEverything.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/readGffFileWithEverything.cpp.i
.PHONY : src/impl/readGffFileWithEverything.cpp.i

src/impl/readGffFileWithEverything.s: src/impl/readGffFileWithEverything.cpp.s

.PHONY : src/impl/readGffFileWithEverything.s

# target to generate assembly for a file
src/impl/readGffFileWithEverything.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/readGffFileWithEverything.cpp.s
.PHONY : src/impl/readGffFileWithEverything.cpp.s

src/impl/readSdiFile.o: src/impl/readSdiFile.cpp.o

.PHONY : src/impl/readSdiFile.o

# target to build an object file
src/impl/readSdiFile.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/readSdiFile.cpp.o
.PHONY : src/impl/readSdiFile.cpp.o

src/impl/readSdiFile.i: src/impl/readSdiFile.cpp.i

.PHONY : src/impl/readSdiFile.i

# target to preprocess a source file
src/impl/readSdiFile.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/readSdiFile.cpp.i
.PHONY : src/impl/readSdiFile.cpp.i

src/impl/readSdiFile.s: src/impl/readSdiFile.cpp.s

.PHONY : src/impl/readSdiFile.s

# target to generate assembly for a file
src/impl/readSdiFile.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/impl/readSdiFile.cpp.s
.PHONY : src/impl/readSdiFile.cpp.s

src/model/AlignmentMatch.o: src/model/AlignmentMatch.cpp.o

.PHONY : src/model/AlignmentMatch.o

# target to build an object file
src/model/AlignmentMatch.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/AlignmentMatch.cpp.o
.PHONY : src/model/AlignmentMatch.cpp.o

src/model/AlignmentMatch.i: src/model/AlignmentMatch.cpp.i

.PHONY : src/model/AlignmentMatch.i

# target to preprocess a source file
src/model/AlignmentMatch.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/AlignmentMatch.cpp.i
.PHONY : src/model/AlignmentMatch.cpp.i

src/model/AlignmentMatch.s: src/model/AlignmentMatch.cpp.s

.PHONY : src/model/AlignmentMatch.s

# target to generate assembly for a file
src/model/AlignmentMatch.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/AlignmentMatch.cpp.s
.PHONY : src/model/AlignmentMatch.cpp.s

src/model/Fasta.o: src/model/Fasta.cpp.o

.PHONY : src/model/Fasta.o

# target to build an object file
src/model/Fasta.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/Fasta.cpp.o
.PHONY : src/model/Fasta.cpp.o

src/model/Fasta.i: src/model/Fasta.cpp.i

.PHONY : src/model/Fasta.i

# target to preprocess a source file
src/model/Fasta.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/Fasta.cpp.i
.PHONY : src/model/Fasta.cpp.i

src/model/Fasta.s: src/model/Fasta.cpp.s

.PHONY : src/model/Fasta.s

# target to generate assembly for a file
src/model/Fasta.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/Fasta.cpp.s
.PHONY : src/model/Fasta.cpp.s

src/model/FirstLastList.o: src/model/FirstLastList.cpp.o

.PHONY : src/model/FirstLastList.o

# target to build an object file
src/model/FirstLastList.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/FirstLastList.cpp.o
.PHONY : src/model/FirstLastList.cpp.o

src/model/FirstLastList.i: src/model/FirstLastList.cpp.i

.PHONY : src/model/FirstLastList.i

# target to preprocess a source file
src/model/FirstLastList.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/FirstLastList.cpp.i
.PHONY : src/model/FirstLastList.cpp.i

src/model/FirstLastList.s: src/model/FirstLastList.cpp.s

.PHONY : src/model/FirstLastList.s

# target to generate assembly for a file
src/model/FirstLastList.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/FirstLastList.cpp.s
.PHONY : src/model/FirstLastList.cpp.s

src/model/Gene.o: src/model/Gene.cpp.o

.PHONY : src/model/Gene.o

# target to build an object file
src/model/Gene.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/Gene.cpp.o
.PHONY : src/model/Gene.cpp.o

src/model/Gene.i: src/model/Gene.cpp.i

.PHONY : src/model/Gene.i

# target to preprocess a source file
src/model/Gene.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/Gene.cpp.i
.PHONY : src/model/Gene.cpp.i

src/model/Gene.s: src/model/Gene.cpp.s

.PHONY : src/model/Gene.s

# target to generate assembly for a file
src/model/Gene.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/Gene.cpp.s
.PHONY : src/model/Gene.cpp.s

src/model/GenomeBasicFeature.o: src/model/GenomeBasicFeature.cpp.o

.PHONY : src/model/GenomeBasicFeature.o

# target to build an object file
src/model/GenomeBasicFeature.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/GenomeBasicFeature.cpp.o
.PHONY : src/model/GenomeBasicFeature.cpp.o

src/model/GenomeBasicFeature.i: src/model/GenomeBasicFeature.cpp.i

.PHONY : src/model/GenomeBasicFeature.i

# target to preprocess a source file
src/model/GenomeBasicFeature.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/GenomeBasicFeature.cpp.i
.PHONY : src/model/GenomeBasicFeature.cpp.i

src/model/GenomeBasicFeature.s: src/model/GenomeBasicFeature.cpp.s

.PHONY : src/model/GenomeBasicFeature.s

# target to generate assembly for a file
src/model/GenomeBasicFeature.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/GenomeBasicFeature.cpp.s
.PHONY : src/model/GenomeBasicFeature.cpp.s

src/model/MsaFileRecord.o: src/model/MsaFileRecord.cpp.o

.PHONY : src/model/MsaFileRecord.o

# target to build an object file
src/model/MsaFileRecord.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/MsaFileRecord.cpp.o
.PHONY : src/model/MsaFileRecord.cpp.o

src/model/MsaFileRecord.i: src/model/MsaFileRecord.cpp.i

.PHONY : src/model/MsaFileRecord.i

# target to preprocess a source file
src/model/MsaFileRecord.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/MsaFileRecord.cpp.i
.PHONY : src/model/MsaFileRecord.cpp.i

src/model/MsaFileRecord.s: src/model/MsaFileRecord.cpp.s

.PHONY : src/model/MsaFileRecord.s

# target to generate assembly for a file
src/model/MsaFileRecord.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/MsaFileRecord.cpp.s
.PHONY : src/model/MsaFileRecord.cpp.s

src/model/MsaSingleRecord.o: src/model/MsaSingleRecord.cpp.o

.PHONY : src/model/MsaSingleRecord.o

# target to build an object file
src/model/MsaSingleRecord.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/MsaSingleRecord.cpp.o
.PHONY : src/model/MsaSingleRecord.cpp.o

src/model/MsaSingleRecord.i: src/model/MsaSingleRecord.cpp.i

.PHONY : src/model/MsaSingleRecord.i

# target to preprocess a source file
src/model/MsaSingleRecord.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/MsaSingleRecord.cpp.i
.PHONY : src/model/MsaSingleRecord.cpp.i

src/model/MsaSingleRecord.s: src/model/MsaSingleRecord.cpp.s

.PHONY : src/model/MsaSingleRecord.s

# target to generate assembly for a file
src/model/MsaSingleRecord.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/MsaSingleRecord.cpp.s
.PHONY : src/model/MsaSingleRecord.cpp.s

src/model/MsaWindow.o: src/model/MsaWindow.cpp.o

.PHONY : src/model/MsaWindow.o

# target to build an object file
src/model/MsaWindow.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/MsaWindow.cpp.o
.PHONY : src/model/MsaWindow.cpp.o

src/model/MsaWindow.i: src/model/MsaWindow.cpp.i

.PHONY : src/model/MsaWindow.i

# target to preprocess a source file
src/model/MsaWindow.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/MsaWindow.cpp.i
.PHONY : src/model/MsaWindow.cpp.i

src/model/MsaWindow.s: src/model/MsaWindow.cpp.s

.PHONY : src/model/MsaWindow.s

# target to generate assembly for a file
src/model/MsaWindow.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/MsaWindow.cpp.s
.PHONY : src/model/MsaWindow.cpp.s

src/model/Range.o: src/model/Range.cpp.o

.PHONY : src/model/Range.o

# target to build an object file
src/model/Range.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/Range.cpp.o
.PHONY : src/model/Range.cpp.o

src/model/Range.i: src/model/Range.cpp.i

.PHONY : src/model/Range.i

# target to preprocess a source file
src/model/Range.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/Range.cpp.i
.PHONY : src/model/Range.cpp.i

src/model/Range.s: src/model/Range.cpp.s

.PHONY : src/model/Range.s

# target to generate assembly for a file
src/model/Range.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/Range.cpp.s
.PHONY : src/model/Range.cpp.s

src/model/Transcript.o: src/model/Transcript.cpp.o

.PHONY : src/model/Transcript.o

# target to build an object file
src/model/Transcript.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/Transcript.cpp.o
.PHONY : src/model/Transcript.cpp.o

src/model/Transcript.i: src/model/Transcript.cpp.i

.PHONY : src/model/Transcript.i

# target to preprocess a source file
src/model/Transcript.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/Transcript.cpp.i
.PHONY : src/model/Transcript.cpp.i

src/model/Transcript.s: src/model/Transcript.cpp.s

.PHONY : src/model/Transcript.s

# target to generate assembly for a file
src/model/Transcript.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/Transcript.cpp.s
.PHONY : src/model/Transcript.cpp.s

src/model/TwoSeqOfMsaResult.o: src/model/TwoSeqOfMsaResult.cpp.o

.PHONY : src/model/TwoSeqOfMsaResult.o

# target to build an object file
src/model/TwoSeqOfMsaResult.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/TwoSeqOfMsaResult.cpp.o
.PHONY : src/model/TwoSeqOfMsaResult.cpp.o

src/model/TwoSeqOfMsaResult.i: src/model/TwoSeqOfMsaResult.cpp.i

.PHONY : src/model/TwoSeqOfMsaResult.i

# target to preprocess a source file
src/model/TwoSeqOfMsaResult.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/TwoSeqOfMsaResult.cpp.i
.PHONY : src/model/TwoSeqOfMsaResult.cpp.i

src/model/TwoSeqOfMsaResult.s: src/model/TwoSeqOfMsaResult.cpp.s

.PHONY : src/model/TwoSeqOfMsaResult.s

# target to generate assembly for a file
src/model/TwoSeqOfMsaResult.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/TwoSeqOfMsaResult.cpp.s
.PHONY : src/model/TwoSeqOfMsaResult.cpp.s

src/model/variant.o: src/model/variant.cpp.o

.PHONY : src/model/variant.o

# target to build an object file
src/model/variant.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/variant.cpp.o
.PHONY : src/model/variant.cpp.o

src/model/variant.i: src/model/variant.cpp.i

.PHONY : src/model/variant.i

# target to preprocess a source file
src/model/variant.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/variant.cpp.i
.PHONY : src/model/variant.cpp.i

src/model/variant.s: src/model/variant.cpp.s

.PHONY : src/model/variant.s

# target to generate assembly for a file
src/model/variant.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/model/variant.cpp.s
.PHONY : src/model/variant.cpp.s

src/myImportandFunction/alignNeedlemanForTranscript.o: src/myImportandFunction/alignNeedlemanForTranscript.cpp.o

.PHONY : src/myImportandFunction/alignNeedlemanForTranscript.o

# target to build an object file
src/myImportandFunction/alignNeedlemanForTranscript.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanForTranscript.cpp.o
.PHONY : src/myImportandFunction/alignNeedlemanForTranscript.cpp.o

src/myImportandFunction/alignNeedlemanForTranscript.i: src/myImportandFunction/alignNeedlemanForTranscript.cpp.i

.PHONY : src/myImportandFunction/alignNeedlemanForTranscript.i

# target to preprocess a source file
src/myImportandFunction/alignNeedlemanForTranscript.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanForTranscript.cpp.i
.PHONY : src/myImportandFunction/alignNeedlemanForTranscript.cpp.i

src/myImportandFunction/alignNeedlemanForTranscript.s: src/myImportandFunction/alignNeedlemanForTranscript.cpp.s

.PHONY : src/myImportandFunction/alignNeedlemanForTranscript.s

# target to generate assembly for a file
src/myImportandFunction/alignNeedlemanForTranscript.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanForTranscript.cpp.s
.PHONY : src/myImportandFunction/alignNeedlemanForTranscript.cpp.s

src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.o: src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.cpp.o

.PHONY : src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.o

# target to build an object file
src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.cpp.o
.PHONY : src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.cpp.o

src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.i: src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.cpp.i

.PHONY : src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.i

# target to preprocess a source file
src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.cpp.i
.PHONY : src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.cpp.i

src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.s: src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.cpp.s

.PHONY : src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.s

# target to generate assembly for a file
src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.cpp.s
.PHONY : src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.cpp.s

src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.o: src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.o

.PHONY : src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.o

# target to build an object file
src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.o
.PHONY : src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.o

src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.i: src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.i

.PHONY : src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.i

# target to preprocess a source file
src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.i
.PHONY : src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.i

src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.s: src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.s

.PHONY : src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.s

# target to generate assembly for a file
src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.s
.PHONY : src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.s

src/myImportandFunction/alignNeedlemanWunsch_simd.o: src/myImportandFunction/alignNeedlemanWunsch_simd.cpp.o

.PHONY : src/myImportandFunction/alignNeedlemanWunsch_simd.o

# target to build an object file
src/myImportandFunction/alignNeedlemanWunsch_simd.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanWunsch_simd.cpp.o
.PHONY : src/myImportandFunction/alignNeedlemanWunsch_simd.cpp.o

src/myImportandFunction/alignNeedlemanWunsch_simd.i: src/myImportandFunction/alignNeedlemanWunsch_simd.cpp.i

.PHONY : src/myImportandFunction/alignNeedlemanWunsch_simd.i

# target to preprocess a source file
src/myImportandFunction/alignNeedlemanWunsch_simd.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanWunsch_simd.cpp.i
.PHONY : src/myImportandFunction/alignNeedlemanWunsch_simd.cpp.i

src/myImportandFunction/alignNeedlemanWunsch_simd.s: src/myImportandFunction/alignNeedlemanWunsch_simd.cpp.s

.PHONY : src/myImportandFunction/alignNeedlemanWunsch_simd.s

# target to generate assembly for a file
src/myImportandFunction/alignNeedlemanWunsch_simd.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanWunsch_simd.cpp.s
.PHONY : src/myImportandFunction/alignNeedlemanWunsch_simd.cpp.s

src/myImportandFunction/alignNeedlemanWunsch_v2.o: src/myImportandFunction/alignNeedlemanWunsch_v2.cpp.o

.PHONY : src/myImportandFunction/alignNeedlemanWunsch_v2.o

# target to build an object file
src/myImportandFunction/alignNeedlemanWunsch_v2.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanWunsch_v2.cpp.o
.PHONY : src/myImportandFunction/alignNeedlemanWunsch_v2.cpp.o

src/myImportandFunction/alignNeedlemanWunsch_v2.i: src/myImportandFunction/alignNeedlemanWunsch_v2.cpp.i

.PHONY : src/myImportandFunction/alignNeedlemanWunsch_v2.i

# target to preprocess a source file
src/myImportandFunction/alignNeedlemanWunsch_v2.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanWunsch_v2.cpp.i
.PHONY : src/myImportandFunction/alignNeedlemanWunsch_v2.cpp.i

src/myImportandFunction/alignNeedlemanWunsch_v2.s: src/myImportandFunction/alignNeedlemanWunsch_v2.cpp.s

.PHONY : src/myImportandFunction/alignNeedlemanWunsch_v2.s

# target to generate assembly for a file
src/myImportandFunction/alignNeedlemanWunsch_v2.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignNeedlemanWunsch_v2.cpp.s
.PHONY : src/myImportandFunction/alignNeedlemanWunsch_v2.cpp.s

src/myImportandFunction/alignSlidingWindow.o: src/myImportandFunction/alignSlidingWindow.cpp.o

.PHONY : src/myImportandFunction/alignSlidingWindow.o

# target to build an object file
src/myImportandFunction/alignSlidingWindow.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignSlidingWindow.cpp.o
.PHONY : src/myImportandFunction/alignSlidingWindow.cpp.o

src/myImportandFunction/alignSlidingWindow.i: src/myImportandFunction/alignSlidingWindow.cpp.i

.PHONY : src/myImportandFunction/alignSlidingWindow.i

# target to preprocess a source file
src/myImportandFunction/alignSlidingWindow.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignSlidingWindow.cpp.i
.PHONY : src/myImportandFunction/alignSlidingWindow.cpp.i

src/myImportandFunction/alignSlidingWindow.s: src/myImportandFunction/alignSlidingWindow.cpp.s

.PHONY : src/myImportandFunction/alignSlidingWindow.s

# target to generate assembly for a file
src/myImportandFunction/alignSlidingWindow.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignSlidingWindow.cpp.s
.PHONY : src/myImportandFunction/alignSlidingWindow.cpp.s

src/myImportandFunction/alignTranscript.o: src/myImportandFunction/alignTranscript.cpp.o

.PHONY : src/myImportandFunction/alignTranscript.o

# target to build an object file
src/myImportandFunction/alignTranscript.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignTranscript.cpp.o
.PHONY : src/myImportandFunction/alignTranscript.cpp.o

src/myImportandFunction/alignTranscript.i: src/myImportandFunction/alignTranscript.cpp.i

.PHONY : src/myImportandFunction/alignTranscript.i

# target to preprocess a source file
src/myImportandFunction/alignTranscript.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignTranscript.cpp.i
.PHONY : src/myImportandFunction/alignTranscript.cpp.i

src/myImportandFunction/alignTranscript.s: src/myImportandFunction/alignTranscript.cpp.s

.PHONY : src/myImportandFunction/alignTranscript.s

# target to generate assembly for a file
src/myImportandFunction/alignTranscript.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/alignTranscript.cpp.s
.PHONY : src/myImportandFunction/alignTranscript.cpp.s

src/myImportandFunction/geneAnnotationAlignment.o: src/myImportandFunction/geneAnnotationAlignment.cpp.o

.PHONY : src/myImportandFunction/geneAnnotationAlignment.o

# target to build an object file
src/myImportandFunction/geneAnnotationAlignment.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/geneAnnotationAlignment.cpp.o
.PHONY : src/myImportandFunction/geneAnnotationAlignment.cpp.o

src/myImportandFunction/geneAnnotationAlignment.i: src/myImportandFunction/geneAnnotationAlignment.cpp.i

.PHONY : src/myImportandFunction/geneAnnotationAlignment.i

# target to preprocess a source file
src/myImportandFunction/geneAnnotationAlignment.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/geneAnnotationAlignment.cpp.i
.PHONY : src/myImportandFunction/geneAnnotationAlignment.cpp.i

src/myImportandFunction/geneAnnotationAlignment.s: src/myImportandFunction/geneAnnotationAlignment.cpp.s

.PHONY : src/myImportandFunction/geneAnnotationAlignment.s

# target to generate assembly for a file
src/myImportandFunction/geneAnnotationAlignment.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/geneAnnotationAlignment.cpp.s
.PHONY : src/myImportandFunction/geneAnnotationAlignment.cpp.s

src/myImportandFunction/hengAlign.o: src/myImportandFunction/hengAlign.cpp.o

.PHONY : src/myImportandFunction/hengAlign.o

# target to build an object file
src/myImportandFunction/hengAlign.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/hengAlign.cpp.o
.PHONY : src/myImportandFunction/hengAlign.cpp.o

src/myImportandFunction/hengAlign.i: src/myImportandFunction/hengAlign.cpp.i

.PHONY : src/myImportandFunction/hengAlign.i

# target to preprocess a source file
src/myImportandFunction/hengAlign.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/hengAlign.cpp.i
.PHONY : src/myImportandFunction/hengAlign.cpp.i

src/myImportandFunction/hengAlign.s: src/myImportandFunction/hengAlign.cpp.s

.PHONY : src/myImportandFunction/hengAlign.s

# target to generate assembly for a file
src/myImportandFunction/hengAlign.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/myImportandFunction/hengAlign.cpp.s
.PHONY : src/myImportandFunction/hengAlign.cpp.s

src/service/MSA/cutWindow.o: src/service/MSA/cutWindow.cpp.o

.PHONY : src/service/MSA/cutWindow.o

# target to build an object file
src/service/MSA/cutWindow.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/MSA/cutWindow.cpp.o
.PHONY : src/service/MSA/cutWindow.cpp.o

src/service/MSA/cutWindow.i: src/service/MSA/cutWindow.cpp.i

.PHONY : src/service/MSA/cutWindow.i

# target to preprocess a source file
src/service/MSA/cutWindow.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/MSA/cutWindow.cpp.i
.PHONY : src/service/MSA/cutWindow.cpp.i

src/service/MSA/cutWindow.s: src/service/MSA/cutWindow.cpp.s

.PHONY : src/service/MSA/cutWindow.s

# target to generate assembly for a file
src/service/MSA/cutWindow.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/MSA/cutWindow.cpp.s
.PHONY : src/service/MSA/cutWindow.cpp.s

src/service/MSA/reSdiFromMsa.o: src/service/MSA/reSdiFromMsa.cpp.o

.PHONY : src/service/MSA/reSdiFromMsa.o

# target to build an object file
src/service/MSA/reSdiFromMsa.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/MSA/reSdiFromMsa.cpp.o
.PHONY : src/service/MSA/reSdiFromMsa.cpp.o

src/service/MSA/reSdiFromMsa.i: src/service/MSA/reSdiFromMsa.cpp.i

.PHONY : src/service/MSA/reSdiFromMsa.i

# target to preprocess a source file
src/service/MSA/reSdiFromMsa.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/MSA/reSdiFromMsa.cpp.i
.PHONY : src/service/MSA/reSdiFromMsa.cpp.i

src/service/MSA/reSdiFromMsa.s: src/service/MSA/reSdiFromMsa.cpp.s

.PHONY : src/service/MSA/reSdiFromMsa.s

# target to generate assembly for a file
src/service/MSA/reSdiFromMsa.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/MSA/reSdiFromMsa.cpp.s
.PHONY : src/service/MSA/reSdiFromMsa.cpp.s

src/service/MSA/transcriptRealignmentPversion.o: src/service/MSA/transcriptRealignmentPversion.cpp.o

.PHONY : src/service/MSA/transcriptRealignmentPversion.o

# target to build an object file
src/service/MSA/transcriptRealignmentPversion.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/MSA/transcriptRealignmentPversion.cpp.o
.PHONY : src/service/MSA/transcriptRealignmentPversion.cpp.o

src/service/MSA/transcriptRealignmentPversion.i: src/service/MSA/transcriptRealignmentPversion.cpp.i

.PHONY : src/service/MSA/transcriptRealignmentPversion.i

# target to preprocess a source file
src/service/MSA/transcriptRealignmentPversion.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/MSA/transcriptRealignmentPversion.cpp.i
.PHONY : src/service/MSA/transcriptRealignmentPversion.cpp.i

src/service/MSA/transcriptRealignmentPversion.s: src/service/MSA/transcriptRealignmentPversion.cpp.s

.PHONY : src/service/MSA/transcriptRealignmentPversion.s

# target to generate assembly for a file
src/service/MSA/transcriptRealignmentPversion.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/MSA/transcriptRealignmentPversion.cpp.s
.PHONY : src/service/MSA/transcriptRealignmentPversion.cpp.s

src/service/TransferGffWithNucmerResult.o: src/service/TransferGffWithNucmerResult.cpp.o

.PHONY : src/service/TransferGffWithNucmerResult.o

# target to build an object file
src/service/TransferGffWithNucmerResult.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/TransferGffWithNucmerResult.cpp.o
.PHONY : src/service/TransferGffWithNucmerResult.cpp.o

src/service/TransferGffWithNucmerResult.i: src/service/TransferGffWithNucmerResult.cpp.i

.PHONY : src/service/TransferGffWithNucmerResult.i

# target to preprocess a source file
src/service/TransferGffWithNucmerResult.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/TransferGffWithNucmerResult.cpp.i
.PHONY : src/service/TransferGffWithNucmerResult.cpp.i

src/service/TransferGffWithNucmerResult.s: src/service/TransferGffWithNucmerResult.cpp.s

.PHONY : src/service/TransferGffWithNucmerResult.s

# target to generate assembly for a file
src/service/TransferGffWithNucmerResult.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/TransferGffWithNucmerResult.cpp.s
.PHONY : src/service/TransferGffWithNucmerResult.cpp.s

src/service/UpdateVariants.o: src/service/UpdateVariants.cpp.o

.PHONY : src/service/UpdateVariants.o

# target to build an object file
src/service/UpdateVariants.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/UpdateVariants.cpp.o
.PHONY : src/service/UpdateVariants.cpp.o

src/service/UpdateVariants.i: src/service/UpdateVariants.cpp.i

.PHONY : src/service/UpdateVariants.i

# target to preprocess a source file
src/service/UpdateVariants.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/UpdateVariants.cpp.i
.PHONY : src/service/UpdateVariants.cpp.i

src/service/UpdateVariants.s: src/service/UpdateVariants.cpp.s

.PHONY : src/service/UpdateVariants.s

# target to generate assembly for a file
src/service/UpdateVariants.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/UpdateVariants.cpp.s
.PHONY : src/service/UpdateVariants.cpp.s

src/service/deNovoGenomeVariantCallingService.o: src/service/deNovoGenomeVariantCallingService.cpp.o

.PHONY : src/service/deNovoGenomeVariantCallingService.o

# target to build an object file
src/service/deNovoGenomeVariantCallingService.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/deNovoGenomeVariantCallingService.cpp.o
.PHONY : src/service/deNovoGenomeVariantCallingService.cpp.o

src/service/deNovoGenomeVariantCallingService.i: src/service/deNovoGenomeVariantCallingService.cpp.i

.PHONY : src/service/deNovoGenomeVariantCallingService.i

# target to preprocess a source file
src/service/deNovoGenomeVariantCallingService.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/deNovoGenomeVariantCallingService.cpp.i
.PHONY : src/service/deNovoGenomeVariantCallingService.cpp.i

src/service/deNovoGenomeVariantCallingService.s: src/service/deNovoGenomeVariantCallingService.cpp.s

.PHONY : src/service/deNovoGenomeVariantCallingService.s

# target to generate assembly for a file
src/service/deNovoGenomeVariantCallingService.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/deNovoGenomeVariantCallingService.cpp.s
.PHONY : src/service/deNovoGenomeVariantCallingService.cpp.s

src/service/denovoGffLiftOverToUniqGffOutput.o: src/service/denovoGffLiftOverToUniqGffOutput.cpp.o

.PHONY : src/service/denovoGffLiftOverToUniqGffOutput.o

# target to build an object file
src/service/denovoGffLiftOverToUniqGffOutput.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/denovoGffLiftOverToUniqGffOutput.cpp.o
.PHONY : src/service/denovoGffLiftOverToUniqGffOutput.cpp.o

src/service/denovoGffLiftOverToUniqGffOutput.i: src/service/denovoGffLiftOverToUniqGffOutput.cpp.i

.PHONY : src/service/denovoGffLiftOverToUniqGffOutput.i

# target to preprocess a source file
src/service/denovoGffLiftOverToUniqGffOutput.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/denovoGffLiftOverToUniqGffOutput.cpp.i
.PHONY : src/service/denovoGffLiftOverToUniqGffOutput.cpp.i

src/service/denovoGffLiftOverToUniqGffOutput.s: src/service/denovoGffLiftOverToUniqGffOutput.cpp.s

.PHONY : src/service/denovoGffLiftOverToUniqGffOutput.s

# target to generate assembly for a file
src/service/denovoGffLiftOverToUniqGffOutput.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/denovoGffLiftOverToUniqGffOutput.cpp.s
.PHONY : src/service/denovoGffLiftOverToUniqGffOutput.cpp.s

src/service/reannotation/TranscriptsTogenes.o: src/service/reannotation/TranscriptsTogenes.cpp.o

.PHONY : src/service/reannotation/TranscriptsTogenes.o

# target to build an object file
src/service/reannotation/TranscriptsTogenes.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/reannotation/TranscriptsTogenes.cpp.o
.PHONY : src/service/reannotation/TranscriptsTogenes.cpp.o

src/service/reannotation/TranscriptsTogenes.i: src/service/reannotation/TranscriptsTogenes.cpp.i

.PHONY : src/service/reannotation/TranscriptsTogenes.i

# target to preprocess a source file
src/service/reannotation/TranscriptsTogenes.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/reannotation/TranscriptsTogenes.cpp.i
.PHONY : src/service/reannotation/TranscriptsTogenes.cpp.i

src/service/reannotation/TranscriptsTogenes.s: src/service/reannotation/TranscriptsTogenes.cpp.s

.PHONY : src/service/reannotation/TranscriptsTogenes.s

# target to generate assembly for a file
src/service/reannotation/TranscriptsTogenes.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/reannotation/TranscriptsTogenes.cpp.s
.PHONY : src/service/reannotation/TranscriptsTogenes.cpp.s

src/service/reannotation/reAnnotationAndExonerateAndNovo.o: src/service/reannotation/reAnnotationAndExonerateAndNovo.cpp.o

.PHONY : src/service/reannotation/reAnnotationAndExonerateAndNovo.o

# target to build an object file
src/service/reannotation/reAnnotationAndExonerateAndNovo.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/reannotation/reAnnotationAndExonerateAndNovo.cpp.o
.PHONY : src/service/reannotation/reAnnotationAndExonerateAndNovo.cpp.o

src/service/reannotation/reAnnotationAndExonerateAndNovo.i: src/service/reannotation/reAnnotationAndExonerateAndNovo.cpp.i

.PHONY : src/service/reannotation/reAnnotationAndExonerateAndNovo.i

# target to preprocess a source file
src/service/reannotation/reAnnotationAndExonerateAndNovo.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/reannotation/reAnnotationAndExonerateAndNovo.cpp.i
.PHONY : src/service/reannotation/reAnnotationAndExonerateAndNovo.cpp.i

src/service/reannotation/reAnnotationAndExonerateAndNovo.s: src/service/reannotation/reAnnotationAndExonerateAndNovo.cpp.s

.PHONY : src/service/reannotation/reAnnotationAndExonerateAndNovo.s

# target to generate assembly for a file
src/service/reannotation/reAnnotationAndExonerateAndNovo.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/reannotation/reAnnotationAndExonerateAndNovo.cpp.s
.PHONY : src/service/reannotation/reAnnotationAndExonerateAndNovo.cpp.s

src/service/reannotation/runExonerate.o: src/service/reannotation/runExonerate.cpp.o

.PHONY : src/service/reannotation/runExonerate.o

# target to build an object file
src/service/reannotation/runExonerate.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/reannotation/runExonerate.cpp.o
.PHONY : src/service/reannotation/runExonerate.cpp.o

src/service/reannotation/runExonerate.i: src/service/reannotation/runExonerate.cpp.i

.PHONY : src/service/reannotation/runExonerate.i

# target to preprocess a source file
src/service/reannotation/runExonerate.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/reannotation/runExonerate.cpp.i
.PHONY : src/service/reannotation/runExonerate.cpp.i

src/service/reannotation/runExonerate.s: src/service/reannotation/runExonerate.cpp.s

.PHONY : src/service/reannotation/runExonerate.s

# target to generate assembly for a file
src/service/reannotation/runExonerate.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/reannotation/runExonerate.cpp.s
.PHONY : src/service/reannotation/runExonerate.cpp.s

src/service/reannotation/transcriptRealignmentAndExonerate.o: src/service/reannotation/transcriptRealignmentAndExonerate.cpp.o

.PHONY : src/service/reannotation/transcriptRealignmentAndExonerate.o

# target to build an object file
src/service/reannotation/transcriptRealignmentAndExonerate.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/reannotation/transcriptRealignmentAndExonerate.cpp.o
.PHONY : src/service/reannotation/transcriptRealignmentAndExonerate.cpp.o

src/service/reannotation/transcriptRealignmentAndExonerate.i: src/service/reannotation/transcriptRealignmentAndExonerate.cpp.i

.PHONY : src/service/reannotation/transcriptRealignmentAndExonerate.i

# target to preprocess a source file
src/service/reannotation/transcriptRealignmentAndExonerate.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/reannotation/transcriptRealignmentAndExonerate.cpp.i
.PHONY : src/service/reannotation/transcriptRealignmentAndExonerate.cpp.i

src/service/reannotation/transcriptRealignmentAndExonerate.s: src/service/reannotation/transcriptRealignmentAndExonerate.cpp.s

.PHONY : src/service/reannotation/transcriptRealignmentAndExonerate.s

# target to generate assembly for a file
src/service/reannotation/transcriptRealignmentAndExonerate.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/service/reannotation/transcriptRealignmentAndExonerate.cpp.s
.PHONY : src/service/reannotation/transcriptRealignmentAndExonerate.cpp.s

src/song_cns.o: src/song_cns.cpp.o

.PHONY : src/song_cns.o

# target to build an object file
src/song_cns.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/song_cns.cpp.o
.PHONY : src/song_cns.cpp.o

src/song_cns.i: src/song_cns.cpp.i

.PHONY : src/song_cns.i

# target to preprocess a source file
src/song_cns.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/song_cns.cpp.i
.PHONY : src/song_cns.cpp.i

src/song_cns.s: src/song_cns.cpp.s

.PHONY : src/song_cns.s

# target to generate assembly for a file
src/song_cns.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/song_cns.cpp.s
.PHONY : src/song_cns.cpp.s

src/tests/control/myGffCoordinateLiftOver_test.o: src/tests/control/myGffCoordinateLiftOver_test.cpp.o

.PHONY : src/tests/control/myGffCoordinateLiftOver_test.o

# target to build an object file
src/tests/control/myGffCoordinateLiftOver_test.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/control/myGffCoordinateLiftOver_test.cpp.o
.PHONY : src/tests/control/myGffCoordinateLiftOver_test.cpp.o

src/tests/control/myGffCoordinateLiftOver_test.i: src/tests/control/myGffCoordinateLiftOver_test.cpp.i

.PHONY : src/tests/control/myGffCoordinateLiftOver_test.i

# target to preprocess a source file
src/tests/control/myGffCoordinateLiftOver_test.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/control/myGffCoordinateLiftOver_test.cpp.i
.PHONY : src/tests/control/myGffCoordinateLiftOver_test.cpp.i

src/tests/control/myGffCoordinateLiftOver_test.s: src/tests/control/myGffCoordinateLiftOver_test.cpp.s

.PHONY : src/tests/control/myGffCoordinateLiftOver_test.s

# target to generate assembly for a file
src/tests/control/myGffCoordinateLiftOver_test.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/control/myGffCoordinateLiftOver_test.cpp.s
.PHONY : src/tests/control/myGffCoordinateLiftOver_test.cpp.s

src/tests/control/myReAnnotationAndExonerateAndNovo_test.o: src/tests/control/myReAnnotationAndExonerateAndNovo_test.cpp.o

.PHONY : src/tests/control/myReAnnotationAndExonerateAndNovo_test.o

# target to build an object file
src/tests/control/myReAnnotationAndExonerateAndNovo_test.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/control/myReAnnotationAndExonerateAndNovo_test.cpp.o
.PHONY : src/tests/control/myReAnnotationAndExonerateAndNovo_test.cpp.o

src/tests/control/myReAnnotationAndExonerateAndNovo_test.i: src/tests/control/myReAnnotationAndExonerateAndNovo_test.cpp.i

.PHONY : src/tests/control/myReAnnotationAndExonerateAndNovo_test.i

# target to preprocess a source file
src/tests/control/myReAnnotationAndExonerateAndNovo_test.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/control/myReAnnotationAndExonerateAndNovo_test.cpp.i
.PHONY : src/tests/control/myReAnnotationAndExonerateAndNovo_test.cpp.i

src/tests/control/myReAnnotationAndExonerateAndNovo_test.s: src/tests/control/myReAnnotationAndExonerateAndNovo_test.cpp.s

.PHONY : src/tests/control/myReAnnotationAndExonerateAndNovo_test.s

# target to generate assembly for a file
src/tests/control/myReAnnotationAndExonerateAndNovo_test.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/control/myReAnnotationAndExonerateAndNovo_test.cpp.s
.PHONY : src/tests/control/myReAnnotationAndExonerateAndNovo_test.cpp.s

src/tests/impl/readFastaFile_test.o: src/tests/impl/readFastaFile_test.cpp.o

.PHONY : src/tests/impl/readFastaFile_test.o

# target to build an object file
src/tests/impl/readFastaFile_test.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/impl/readFastaFile_test.cpp.o
.PHONY : src/tests/impl/readFastaFile_test.cpp.o

src/tests/impl/readFastaFile_test.i: src/tests/impl/readFastaFile_test.cpp.i

.PHONY : src/tests/impl/readFastaFile_test.i

# target to preprocess a source file
src/tests/impl/readFastaFile_test.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/impl/readFastaFile_test.cpp.i
.PHONY : src/tests/impl/readFastaFile_test.cpp.i

src/tests/impl/readFastaFile_test.s: src/tests/impl/readFastaFile_test.cpp.s

.PHONY : src/tests/impl/readFastaFile_test.s

# target to generate assembly for a file
src/tests/impl/readFastaFile_test.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/impl/readFastaFile_test.cpp.s
.PHONY : src/tests/impl/readFastaFile_test.cpp.s

src/tests/impl/readGffFileWithEverything.o: src/tests/impl/readGffFileWithEverything.cpp.o

.PHONY : src/tests/impl/readGffFileWithEverything.o

# target to build an object file
src/tests/impl/readGffFileWithEverything.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/impl/readGffFileWithEverything.cpp.o
.PHONY : src/tests/impl/readGffFileWithEverything.cpp.o

src/tests/impl/readGffFileWithEverything.i: src/tests/impl/readGffFileWithEverything.cpp.i

.PHONY : src/tests/impl/readGffFileWithEverything.i

# target to preprocess a source file
src/tests/impl/readGffFileWithEverything.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/impl/readGffFileWithEverything.cpp.i
.PHONY : src/tests/impl/readGffFileWithEverything.cpp.i

src/tests/impl/readGffFileWithEverything.s: src/tests/impl/readGffFileWithEverything.cpp.s

.PHONY : src/tests/impl/readGffFileWithEverything.s

# target to generate assembly for a file
src/tests/impl/readGffFileWithEverything.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/impl/readGffFileWithEverything.cpp.s
.PHONY : src/tests/impl/readGffFileWithEverything.cpp.s

src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.o: src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.o

.PHONY : src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.o

# target to build an object file
src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.o
.PHONY : src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.o

src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.i: src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.i

.PHONY : src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.i

# target to preprocess a source file
src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.i
.PHONY : src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.i

src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.s: src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.s

.PHONY : src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.s

# target to generate assembly for a file
src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.s
.PHONY : src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.cpp.s

src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.o: src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.cpp.o

.PHONY : src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.o

# target to build an object file
src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.cpp.o
.PHONY : src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.cpp.o

src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.i: src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.cpp.i

.PHONY : src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.i

# target to preprocess a source file
src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.cpp.i
.PHONY : src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.cpp.i

src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.s: src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.cpp.s

.PHONY : src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.s

# target to generate assembly for a file
src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.cpp.s
.PHONY : src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.cpp.s

src/tests/myImportandFunction/alignSlidingWindow_test.o: src/tests/myImportandFunction/alignSlidingWindow_test.cpp.o

.PHONY : src/tests/myImportandFunction/alignSlidingWindow_test.o

# target to build an object file
src/tests/myImportandFunction/alignSlidingWindow_test.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/alignSlidingWindow_test.cpp.o
.PHONY : src/tests/myImportandFunction/alignSlidingWindow_test.cpp.o

src/tests/myImportandFunction/alignSlidingWindow_test.i: src/tests/myImportandFunction/alignSlidingWindow_test.cpp.i

.PHONY : src/tests/myImportandFunction/alignSlidingWindow_test.i

# target to preprocess a source file
src/tests/myImportandFunction/alignSlidingWindow_test.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/alignSlidingWindow_test.cpp.i
.PHONY : src/tests/myImportandFunction/alignSlidingWindow_test.cpp.i

src/tests/myImportandFunction/alignSlidingWindow_test.s: src/tests/myImportandFunction/alignSlidingWindow_test.cpp.s

.PHONY : src/tests/myImportandFunction/alignSlidingWindow_test.s

# target to generate assembly for a file
src/tests/myImportandFunction/alignSlidingWindow_test.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/alignSlidingWindow_test.cpp.s
.PHONY : src/tests/myImportandFunction/alignSlidingWindow_test.cpp.s

src/tests/myImportandFunction/alignTranscript.o: src/tests/myImportandFunction/alignTranscript.cpp.o

.PHONY : src/tests/myImportandFunction/alignTranscript.o

# target to build an object file
src/tests/myImportandFunction/alignTranscript.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/alignTranscript.cpp.o
.PHONY : src/tests/myImportandFunction/alignTranscript.cpp.o

src/tests/myImportandFunction/alignTranscript.i: src/tests/myImportandFunction/alignTranscript.cpp.i

.PHONY : src/tests/myImportandFunction/alignTranscript.i

# target to preprocess a source file
src/tests/myImportandFunction/alignTranscript.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/alignTranscript.cpp.i
.PHONY : src/tests/myImportandFunction/alignTranscript.cpp.i

src/tests/myImportandFunction/alignTranscript.s: src/tests/myImportandFunction/alignTranscript.cpp.s

.PHONY : src/tests/myImportandFunction/alignTranscript.s

# target to generate assembly for a file
src/tests/myImportandFunction/alignTranscript.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/alignTranscript.cpp.s
.PHONY : src/tests/myImportandFunction/alignTranscript.cpp.s

src/tests/myImportandFunction/hengAlign_test.o: src/tests/myImportandFunction/hengAlign_test.cpp.o

.PHONY : src/tests/myImportandFunction/hengAlign_test.o

# target to build an object file
src/tests/myImportandFunction/hengAlign_test.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/hengAlign_test.cpp.o
.PHONY : src/tests/myImportandFunction/hengAlign_test.cpp.o

src/tests/myImportandFunction/hengAlign_test.i: src/tests/myImportandFunction/hengAlign_test.cpp.i

.PHONY : src/tests/myImportandFunction/hengAlign_test.i

# target to preprocess a source file
src/tests/myImportandFunction/hengAlign_test.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/hengAlign_test.cpp.i
.PHONY : src/tests/myImportandFunction/hengAlign_test.cpp.i

src/tests/myImportandFunction/hengAlign_test.s: src/tests/myImportandFunction/hengAlign_test.cpp.s

.PHONY : src/tests/myImportandFunction/hengAlign_test.s

# target to generate assembly for a file
src/tests/myImportandFunction/hengAlign_test.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/myImportandFunction/hengAlign_test.cpp.s
.PHONY : src/tests/myImportandFunction/hengAlign_test.cpp.s

src/tests/service/TransferGffWithNucmerResult_test.o: src/tests/service/TransferGffWithNucmerResult_test.cpp.o

.PHONY : src/tests/service/TransferGffWithNucmerResult_test.o

# target to build an object file
src/tests/service/TransferGffWithNucmerResult_test.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/service/TransferGffWithNucmerResult_test.cpp.o
.PHONY : src/tests/service/TransferGffWithNucmerResult_test.cpp.o

src/tests/service/TransferGffWithNucmerResult_test.i: src/tests/service/TransferGffWithNucmerResult_test.cpp.i

.PHONY : src/tests/service/TransferGffWithNucmerResult_test.i

# target to preprocess a source file
src/tests/service/TransferGffWithNucmerResult_test.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/service/TransferGffWithNucmerResult_test.cpp.i
.PHONY : src/tests/service/TransferGffWithNucmerResult_test.cpp.i

src/tests/service/TransferGffWithNucmerResult_test.s: src/tests/service/TransferGffWithNucmerResult_test.cpp.s

.PHONY : src/tests/service/TransferGffWithNucmerResult_test.s

# target to generate assembly for a file
src/tests/service/TransferGffWithNucmerResult_test.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/service/TransferGffWithNucmerResult_test.cpp.s
.PHONY : src/tests/service/TransferGffWithNucmerResult_test.cpp.s

src/tests/service/UpdateVariants_test.o: src/tests/service/UpdateVariants_test.cpp.o

.PHONY : src/tests/service/UpdateVariants_test.o

# target to build an object file
src/tests/service/UpdateVariants_test.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/service/UpdateVariants_test.cpp.o
.PHONY : src/tests/service/UpdateVariants_test.cpp.o

src/tests/service/UpdateVariants_test.i: src/tests/service/UpdateVariants_test.cpp.i

.PHONY : src/tests/service/UpdateVariants_test.i

# target to preprocess a source file
src/tests/service/UpdateVariants_test.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/service/UpdateVariants_test.cpp.i
.PHONY : src/tests/service/UpdateVariants_test.cpp.i

src/tests/service/UpdateVariants_test.s: src/tests/service/UpdateVariants_test.cpp.s

.PHONY : src/tests/service/UpdateVariants_test.s

# target to generate assembly for a file
src/tests/service/UpdateVariants_test.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/service/UpdateVariants_test.cpp.s
.PHONY : src/tests/service/UpdateVariants_test.cpp.s

src/tests/std/bitsetTest.o: src/tests/std/bitsetTest.cpp.o

.PHONY : src/tests/std/bitsetTest.o

# target to build an object file
src/tests/std/bitsetTest.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/std/bitsetTest.cpp.o
.PHONY : src/tests/std/bitsetTest.cpp.o

src/tests/std/bitsetTest.i: src/tests/std/bitsetTest.cpp.i

.PHONY : src/tests/std/bitsetTest.i

# target to preprocess a source file
src/tests/std/bitsetTest.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/std/bitsetTest.cpp.i
.PHONY : src/tests/std/bitsetTest.cpp.i

src/tests/std/bitsetTest.s: src/tests/std/bitsetTest.cpp.s

.PHONY : src/tests/std/bitsetTest.s

# target to generate assembly for a file
src/tests/std/bitsetTest.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/std/bitsetTest.cpp.s
.PHONY : src/tests/std/bitsetTest.cpp.s

src/tests/util/nucleotideCodeSubstitutionMatrix_test.o: src/tests/util/nucleotideCodeSubstitutionMatrix_test.cpp.o

.PHONY : src/tests/util/nucleotideCodeSubstitutionMatrix_test.o

# target to build an object file
src/tests/util/nucleotideCodeSubstitutionMatrix_test.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/util/nucleotideCodeSubstitutionMatrix_test.cpp.o
.PHONY : src/tests/util/nucleotideCodeSubstitutionMatrix_test.cpp.o

src/tests/util/nucleotideCodeSubstitutionMatrix_test.i: src/tests/util/nucleotideCodeSubstitutionMatrix_test.cpp.i

.PHONY : src/tests/util/nucleotideCodeSubstitutionMatrix_test.i

# target to preprocess a source file
src/tests/util/nucleotideCodeSubstitutionMatrix_test.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/util/nucleotideCodeSubstitutionMatrix_test.cpp.i
.PHONY : src/tests/util/nucleotideCodeSubstitutionMatrix_test.cpp.i

src/tests/util/nucleotideCodeSubstitutionMatrix_test.s: src/tests/util/nucleotideCodeSubstitutionMatrix_test.cpp.s

.PHONY : src/tests/util/nucleotideCodeSubstitutionMatrix_test.s

# target to generate assembly for a file
src/tests/util/nucleotideCodeSubstitutionMatrix_test.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/tests/util/nucleotideCodeSubstitutionMatrix_test.cpp.s
.PHONY : src/tests/util/nucleotideCodeSubstitutionMatrix_test.cpp.s

src/util/myutil.o: src/util/myutil.cpp.o

.PHONY : src/util/myutil.o

# target to build an object file
src/util/myutil.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/util/myutil.cpp.o
.PHONY : src/util/myutil.cpp.o

src/util/myutil.i: src/util/myutil.cpp.i

.PHONY : src/util/myutil.i

# target to preprocess a source file
src/util/myutil.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/util/myutil.cpp.i
.PHONY : src/util/myutil.cpp.i

src/util/myutil.s: src/util/myutil.cpp.s

.PHONY : src/util/myutil.s

# target to generate assembly for a file
src/util/myutil.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/util/myutil.cpp.s
.PHONY : src/util/myutil.cpp.s

src/util/nucleotideCodeSubstitutionMatrix.o: src/util/nucleotideCodeSubstitutionMatrix.cpp.o

.PHONY : src/util/nucleotideCodeSubstitutionMatrix.o

# target to build an object file
src/util/nucleotideCodeSubstitutionMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/util/nucleotideCodeSubstitutionMatrix.cpp.o
.PHONY : src/util/nucleotideCodeSubstitutionMatrix.cpp.o

src/util/nucleotideCodeSubstitutionMatrix.i: src/util/nucleotideCodeSubstitutionMatrix.cpp.i

.PHONY : src/util/nucleotideCodeSubstitutionMatrix.i

# target to preprocess a source file
src/util/nucleotideCodeSubstitutionMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/util/nucleotideCodeSubstitutionMatrix.cpp.i
.PHONY : src/util/nucleotideCodeSubstitutionMatrix.cpp.i

src/util/nucleotideCodeSubstitutionMatrix.s: src/util/nucleotideCodeSubstitutionMatrix.cpp.s

.PHONY : src/util/nucleotideCodeSubstitutionMatrix.s

# target to generate assembly for a file
src/util/nucleotideCodeSubstitutionMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/util/nucleotideCodeSubstitutionMatrix.cpp.s
.PHONY : src/util/nucleotideCodeSubstitutionMatrix.cpp.s

src/util/parameters.o: src/util/parameters.cpp.o

.PHONY : src/util/parameters.o

# target to build an object file
src/util/parameters.cpp.o:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/util/parameters.cpp.o
.PHONY : src/util/parameters.cpp.o

src/util/parameters.i: src/util/parameters.cpp.i

.PHONY : src/util/parameters.i

# target to preprocess a source file
src/util/parameters.cpp.i:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/util/parameters.cpp.i
.PHONY : src/util/parameters.cpp.i

src/util/parameters.s: src/util/parameters.cpp.s

.PHONY : src/util/parameters.s

# target to generate assembly for a file
src/util/parameters.cpp.s:
	$(MAKE) -f CMakeFiles/gean.dir/build.make CMakeFiles/gean.dir/src/util/parameters.cpp.s
.PHONY : src/util/parameters.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... gean"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... song.o"
	@echo "... song.i"
	@echo "... song.s"
	@echo "... src/InputParser.o"
	@echo "... src/InputParser.i"
	@echo "... src/InputParser.s"
	@echo "... src/cns.o"
	@echo "... src/cns.i"
	@echo "... src/cns.s"
	@echo "... src/control/VariantsCountAsPhenotypeForAssociation.o"
	@echo "... src/control/VariantsCountAsPhenotypeForAssociation.i"
	@echo "... src/control/VariantsCountAsPhenotypeForAssociation.s"
	@echo "... src/control/myCoordinateLiftOver.o"
	@echo "... src/control/myCoordinateLiftOver.i"
	@echo "... src/control/myCoordinateLiftOver.s"
	@echo "... src/control/myReAnnotationAndExonerateAndNovo.o"
	@echo "... src/control/myReAnnotationAndExonerateAndNovo.i"
	@echo "... src/control/myReAnnotationAndExonerateAndNovo.s"
	@echo "... src/controlLayer.o"
	@echo "... src/controlLayer.i"
	@echo "... src/controlLayer.s"
	@echo "... src/impl/CheckAndUpdateTranscriptsEnds.o"
	@echo "... src/impl/CheckAndUpdateTranscriptsEnds.i"
	@echo "... src/impl/CheckAndUpdateTranscriptsEnds.s"
	@echo "... src/impl/FileWriteCatch.o"
	@echo "... src/impl/FileWriteCatch.i"
	@echo "... src/impl/FileWriteCatch.s"
	@echo "... src/impl/GetPseudoGenomeSequence.o"
	@echo "... src/impl/GetPseudoGenomeSequence.i"
	@echo "... src/impl/GetPseudoGenomeSequence.s"
	@echo "... src/impl/GetReverseComplementary.o"
	@echo "... src/impl/GetReverseComplementary.i"
	@echo "... src/impl/GetReverseComplementary.s"
	@echo "... src/impl/NucmerRead.o"
	@echo "... src/impl/NucmerRead.i"
	@echo "... src/impl/NucmerRead.s"
	@echo "... src/impl/TranscriptUpdateInformation.o"
	@echo "... src/impl/TranscriptUpdateInformation.i"
	@echo "... src/impl/TranscriptUpdateInformation.s"
	@echo "... src/impl/WriteFasta.o"
	@echo "... src/impl/WriteFasta.i"
	@echo "... src/impl/WriteFasta.s"
	@echo "... src/impl/annotationLiftOver.o"
	@echo "... src/impl/annotationLiftOver.i"
	@echo "... src/impl/annotationLiftOver.s"
	@echo "... src/impl/checkOrfState.o"
	@echo "... src/impl/checkOrfState.i"
	@echo "... src/impl/checkOrfState.s"
	@echo "... src/impl/coordinateLiftOver.o"
	@echo "... src/impl/coordinateLiftOver.i"
	@echo "... src/impl/coordinateLiftOver.s"
	@echo "... src/impl/deNovoGenomeVariantCalling.o"
	@echo "... src/impl/deNovoGenomeVariantCalling.i"
	@echo "... src/impl/deNovoGenomeVariantCalling.s"
	@echo "... src/impl/getSequencesFromGff.o"
	@echo "... src/impl/getSequencesFromGff.i"
	@echo "... src/impl/getSequencesFromGff.s"
	@echo "... src/impl/getSubsequence.o"
	@echo "... src/impl/getSubsequence.i"
	@echo "... src/impl/getSubsequence.s"
	@echo "... src/impl/nA2AA.o"
	@echo "... src/impl/nA2AA.i"
	@echo "... src/impl/nA2AA.s"
	@echo "... src/impl/organizeGffRecords.o"
	@echo "... src/impl/organizeGffRecords.i"
	@echo "... src/impl/organizeGffRecords.s"
	@echo "... src/impl/readFastaFile.o"
	@echo "... src/impl/readFastaFile.i"
	@echo "... src/impl/readFastaFile.s"
	@echo "... src/impl/readGffFile.o"
	@echo "... src/impl/readGffFile.i"
	@echo "... src/impl/readGffFile.s"
	@echo "... src/impl/readGffFileWithEverything.o"
	@echo "... src/impl/readGffFileWithEverything.i"
	@echo "... src/impl/readGffFileWithEverything.s"
	@echo "... src/impl/readSdiFile.o"
	@echo "... src/impl/readSdiFile.i"
	@echo "... src/impl/readSdiFile.s"
	@echo "... src/model/AlignmentMatch.o"
	@echo "... src/model/AlignmentMatch.i"
	@echo "... src/model/AlignmentMatch.s"
	@echo "... src/model/Fasta.o"
	@echo "... src/model/Fasta.i"
	@echo "... src/model/Fasta.s"
	@echo "... src/model/FirstLastList.o"
	@echo "... src/model/FirstLastList.i"
	@echo "... src/model/FirstLastList.s"
	@echo "... src/model/Gene.o"
	@echo "... src/model/Gene.i"
	@echo "... src/model/Gene.s"
	@echo "... src/model/GenomeBasicFeature.o"
	@echo "... src/model/GenomeBasicFeature.i"
	@echo "... src/model/GenomeBasicFeature.s"
	@echo "... src/model/MsaFileRecord.o"
	@echo "... src/model/MsaFileRecord.i"
	@echo "... src/model/MsaFileRecord.s"
	@echo "... src/model/MsaSingleRecord.o"
	@echo "... src/model/MsaSingleRecord.i"
	@echo "... src/model/MsaSingleRecord.s"
	@echo "... src/model/MsaWindow.o"
	@echo "... src/model/MsaWindow.i"
	@echo "... src/model/MsaWindow.s"
	@echo "... src/model/Range.o"
	@echo "... src/model/Range.i"
	@echo "... src/model/Range.s"
	@echo "... src/model/Transcript.o"
	@echo "... src/model/Transcript.i"
	@echo "... src/model/Transcript.s"
	@echo "... src/model/TwoSeqOfMsaResult.o"
	@echo "... src/model/TwoSeqOfMsaResult.i"
	@echo "... src/model/TwoSeqOfMsaResult.s"
	@echo "... src/model/variant.o"
	@echo "... src/model/variant.i"
	@echo "... src/model/variant.s"
	@echo "... src/myImportandFunction/alignNeedlemanForTranscript.o"
	@echo "... src/myImportandFunction/alignNeedlemanForTranscript.i"
	@echo "... src/myImportandFunction/alignNeedlemanForTranscript.s"
	@echo "... src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.o"
	@echo "... src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.i"
	@echo "... src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int16.s"
	@echo "... src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.o"
	@echo "... src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.i"
	@echo "... src/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.s"
	@echo "... src/myImportandFunction/alignNeedlemanWunsch_simd.o"
	@echo "... src/myImportandFunction/alignNeedlemanWunsch_simd.i"
	@echo "... src/myImportandFunction/alignNeedlemanWunsch_simd.s"
	@echo "... src/myImportandFunction/alignNeedlemanWunsch_v2.o"
	@echo "... src/myImportandFunction/alignNeedlemanWunsch_v2.i"
	@echo "... src/myImportandFunction/alignNeedlemanWunsch_v2.s"
	@echo "... src/myImportandFunction/alignSlidingWindow.o"
	@echo "... src/myImportandFunction/alignSlidingWindow.i"
	@echo "... src/myImportandFunction/alignSlidingWindow.s"
	@echo "... src/myImportandFunction/alignTranscript.o"
	@echo "... src/myImportandFunction/alignTranscript.i"
	@echo "... src/myImportandFunction/alignTranscript.s"
	@echo "... src/myImportandFunction/geneAnnotationAlignment.o"
	@echo "... src/myImportandFunction/geneAnnotationAlignment.i"
	@echo "... src/myImportandFunction/geneAnnotationAlignment.s"
	@echo "... src/myImportandFunction/hengAlign.o"
	@echo "... src/myImportandFunction/hengAlign.i"
	@echo "... src/myImportandFunction/hengAlign.s"
	@echo "... src/service/MSA/cutWindow.o"
	@echo "... src/service/MSA/cutWindow.i"
	@echo "... src/service/MSA/cutWindow.s"
	@echo "... src/service/MSA/reSdiFromMsa.o"
	@echo "... src/service/MSA/reSdiFromMsa.i"
	@echo "... src/service/MSA/reSdiFromMsa.s"
	@echo "... src/service/MSA/transcriptRealignmentPversion.o"
	@echo "... src/service/MSA/transcriptRealignmentPversion.i"
	@echo "... src/service/MSA/transcriptRealignmentPversion.s"
	@echo "... src/service/TransferGffWithNucmerResult.o"
	@echo "... src/service/TransferGffWithNucmerResult.i"
	@echo "... src/service/TransferGffWithNucmerResult.s"
	@echo "... src/service/UpdateVariants.o"
	@echo "... src/service/UpdateVariants.i"
	@echo "... src/service/UpdateVariants.s"
	@echo "... src/service/deNovoGenomeVariantCallingService.o"
	@echo "... src/service/deNovoGenomeVariantCallingService.i"
	@echo "... src/service/deNovoGenomeVariantCallingService.s"
	@echo "... src/service/denovoGffLiftOverToUniqGffOutput.o"
	@echo "... src/service/denovoGffLiftOverToUniqGffOutput.i"
	@echo "... src/service/denovoGffLiftOverToUniqGffOutput.s"
	@echo "... src/service/reannotation/TranscriptsTogenes.o"
	@echo "... src/service/reannotation/TranscriptsTogenes.i"
	@echo "... src/service/reannotation/TranscriptsTogenes.s"
	@echo "... src/service/reannotation/reAnnotationAndExonerateAndNovo.o"
	@echo "... src/service/reannotation/reAnnotationAndExonerateAndNovo.i"
	@echo "... src/service/reannotation/reAnnotationAndExonerateAndNovo.s"
	@echo "... src/service/reannotation/runExonerate.o"
	@echo "... src/service/reannotation/runExonerate.i"
	@echo "... src/service/reannotation/runExonerate.s"
	@echo "... src/service/reannotation/transcriptRealignmentAndExonerate.o"
	@echo "... src/service/reannotation/transcriptRealignmentAndExonerate.i"
	@echo "... src/service/reannotation/transcriptRealignmentAndExonerate.s"
	@echo "... src/song_cns.o"
	@echo "... src/song_cns.i"
	@echo "... src/song_cns.s"
	@echo "... src/tests/control/myGffCoordinateLiftOver_test.o"
	@echo "... src/tests/control/myGffCoordinateLiftOver_test.i"
	@echo "... src/tests/control/myGffCoordinateLiftOver_test.s"
	@echo "... src/tests/control/myReAnnotationAndExonerateAndNovo_test.o"
	@echo "... src/tests/control/myReAnnotationAndExonerateAndNovo_test.i"
	@echo "... src/tests/control/myReAnnotationAndExonerateAndNovo_test.s"
	@echo "... src/tests/impl/readFastaFile_test.o"
	@echo "... src/tests/impl/readFastaFile_test.i"
	@echo "... src/tests/impl/readFastaFile_test.s"
	@echo "... src/tests/impl/readGffFileWithEverything.o"
	@echo "... src/tests/impl/readGffFileWithEverything.i"
	@echo "... src/tests/impl/readGffFileWithEverything.s"
	@echo "... src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.o"
	@echo "... src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.i"
	@echo "... src/tests/myImportandFunction/alignNeedlemanForTranscript_simd_avx2int32.s"
	@echo "... src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.o"
	@echo "... src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.i"
	@echo "... src/tests/myImportandFunction/alignNeedlemanWunsch_simd_test.s"
	@echo "... src/tests/myImportandFunction/alignSlidingWindow_test.o"
	@echo "... src/tests/myImportandFunction/alignSlidingWindow_test.i"
	@echo "... src/tests/myImportandFunction/alignSlidingWindow_test.s"
	@echo "... src/tests/myImportandFunction/alignTranscript.o"
	@echo "... src/tests/myImportandFunction/alignTranscript.i"
	@echo "... src/tests/myImportandFunction/alignTranscript.s"
	@echo "... src/tests/myImportandFunction/hengAlign_test.o"
	@echo "... src/tests/myImportandFunction/hengAlign_test.i"
	@echo "... src/tests/myImportandFunction/hengAlign_test.s"
	@echo "... src/tests/service/TransferGffWithNucmerResult_test.o"
	@echo "... src/tests/service/TransferGffWithNucmerResult_test.i"
	@echo "... src/tests/service/TransferGffWithNucmerResult_test.s"
	@echo "... src/tests/service/UpdateVariants_test.o"
	@echo "... src/tests/service/UpdateVariants_test.i"
	@echo "... src/tests/service/UpdateVariants_test.s"
	@echo "... src/tests/std/bitsetTest.o"
	@echo "... src/tests/std/bitsetTest.i"
	@echo "... src/tests/std/bitsetTest.s"
	@echo "... src/tests/util/nucleotideCodeSubstitutionMatrix_test.o"
	@echo "... src/tests/util/nucleotideCodeSubstitutionMatrix_test.i"
	@echo "... src/tests/util/nucleotideCodeSubstitutionMatrix_test.s"
	@echo "... src/util/myutil.o"
	@echo "... src/util/myutil.i"
	@echo "... src/util/myutil.s"
	@echo "... src/util/nucleotideCodeSubstitutionMatrix.o"
	@echo "... src/util/nucleotideCodeSubstitutionMatrix.i"
	@echo "... src/util/nucleotideCodeSubstitutionMatrix.s"
	@echo "... src/util/parameters.o"
	@echo "... src/util/parameters.i"
	@echo "... src/util/parameters.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

